<div id="header" class="top-bar" id="realEstateMenu">
    <div class="top-bar-left ">
        <ul class="menu" data-responsive-menu="accordion">
            <li class="menu-text icon">AA</li>
        </ul>
    </div>

    <div class="top-bar-right">
        <ul class="dropdown menu" data-dropdown-menu>
            <li>
                <a href="#">Dropdown</a>
                <ul class="menu">
                    <li><a href="#">Item 1A</a></li>
                    <li><a href="#">Item 2A</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>