<div class="top-bar" id="realEstateMenu">
    <div class="top-bar-left">
        <ul class="menu" data-responsive-menu="accordion">
            <li class="menu-text">Dashboard</li>
            <li><a href="#">App</a></li>
            <li><a href="#">Feedback</a></li>
            <li><a href="#">Statistics</a></li>
            <li><a href="#">Team</a></li>
        </ul>
    </div>

    <div class="top-bar-right">
        <ul class="menu float-right">
            <li class="menu-text">Timeline</li>
        </ul>
    </div>
</div>